export const UPDATE_POSTS = 'UPDATE_POSTS';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

export const LOG_OUT = 'LOG_OUT';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';

export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';
export const USER_PROFILE_BEGIN = 'USER_PROFILE_BEGIN';

export const CLEAR_PROFILE_STATE = 'CLEAR_PROFILE_STATE';

export const FETCH_USER_FRIENDS_SUCCESS = 'FETCH_USER_FRIENDS_SUCCESS';
export const FETCH_USER_FRIENDS_FAILED = 'FETCH_USER_FRIENDS_FAILED';
export const FETCH_USER_FRIENDS_BEGIN = 'FETCH_USER_FRIENDS_BEGIN';

export const ADD_FRIEND_FAILED = 'ADD_FRIEND_FAILED';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCESS';
export const ADD_FRIEND_BEGIN = 'ADD_FRIEND_BEGIN';

export const REMOVE_FRIEND_FAILED = 'REMOVE_FRIEND_FAILED';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCESS';
export const REMOVE_FRIEND_BEGIN = 'REMOVE_FRIEND_BEGIN';

export const CLEAR_FRIEND_STATE = 'CLEAR_FRIEND_STATE';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILED = 'ADD_POST_FAILED';
export const ADD_POST_BEGIN = 'ADD_POST_BEGIN';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const TOGGLE_LIKE_SUCCESS = 'TOGGLE_LIKE_SUCCESS';
export const TOGGLE_LIKE_FAILED = 'TOGGLE_LIKE_FAILED';

export const FETCH_SEARCH_USERS = 'FETCH_SEARCH_USERS';
export const CLEAR_SERACH = 'CLEAR_SEARCH';
